##
##  Makefile -- Build procedure for sample auth_httprequest Apache module
##  Autogenerated via ``apxs -n auth_httprequest -g''.
##

builddir=.
top_srcdir=/etc/httpd
top_builddir=/usr/lib/httpd
include /usr/lib/httpd/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib
LDFLAGS=-lcurl

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_auth_httprequest.o mod_auth_httprequest.lo mod_auth_httprequest.slo mod_auth_httprequest.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/auth/auth

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: stop install start

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

